### ISSUE TITLE
UnusedTopLevel not actually implemented?

### ISSUE THREAD

**Issue by colinhunt** [stil4m/elm-analyse#67] opened 2017-04-22 20:54 UTC
This doesn't seem to be working, and looking through the src, I can't find the implementation.
>**UnusedTopLevel**	Functions that are unused in a module and not exported are dead code. These should be removed.

**Comment by stil4m** [comment] 2017-04-22 22:15
This functionality is implemented together with some other checks in a single file:

https://github.com/stil4m/elm-analyse/blob/master/src/Analyser/Checks/UnusedVariable.elm#L32

How is this not working for you at the moment? Can you give a small scale example?

**Comment by stil4m** [comment] 2017-05-08 14:18
@colinhunt Could you respond to the previous comment?

**Comment by colinhunt** [comment] 2017-05-11 03:56
Hi @stil4m, sorry for the delay. Here is a minimal example:
```elm
module Main exposing (..)

import Html exposing (text)


main : Html.Html msg
main =
    text "Hello, World!"


foo : a -> a
foo bar =
    bar
```
Running `elm-analyse` produces
```
$ elm-analyse 
INFO: No configuration provided. Using default configuration.
INFO: Load dependency elm-lang/core5.1.1
INFO: Load dependency elm-lang/html2.0.0
INFO: Load file Main.elm...
Messages:
---------
Exposing all in file "Main.elm" at ((1,22),(1,24))
```
I would have expected it to warn me about `foo` being unused.

**Comment by stil4m** [comment] 2017-05-11 07:30
Hi @colinhunt, top levels are not marked as unused if these are exposed.

Fixing the first message `Exposing all in file "Main.elm" at ((1,22),(1,24))`, would probably result in the following header `module Main exposing (..)`. At this point `foo` would be identified as unused top level.

For now this is by design. I have plans to scan the whole project and to recognise that `foo` is not used in the whole project, but there are some challenges with that, for example libraries that expose functions.

**Closed** 2017-06-08 15:20 UTC
