### ISSUE TITLE
Graph rendering fails if code base contains a duplicate import

### ISSUE THREAD

**Issue by pietro909** [stil4m/elm-analyse#112] opened 2017-10-06 16:19 UTC
I can't see the Graph (it is not rendered).

The console says:

`Uncaught The edge "Api-Api<->Models" already exists.`

*Api* and *Models* are two of my modules.

**Comment by stil4m** [comment] 2017-10-06 18:42
That is not good. Could you provide which version of `elm-analyse` you are using? Would it be possible to create a reproducible example? Thanks

**Comment by pietro909** [comment] 2017-10-06 18:59
- version is `0.11.0`
- it is installed locally (I run it with `./node_modules/.bin/elm-analyse"`)
- elm version is 0.18

For the example, I need to work on this a bit because the codebase is closed source.

Thank you for your prompt reply, and for this amazing tool!

**Comment by pietro909** [comment] 2017-10-09 07:34
I've sorted it out: when an import is *duplicated*, it generates the error.

For instance:
```
import Helpers
import Helpers exposing (aHelper)
```

Removing the second import works. I've prepared a [self-contained minimum example here](https://github.com/pietro909/elm-playground/tree/master/elm-analyse-duplicated-import).

**Comment by stil4m** [comment] 2017-10-09 17:58
Good to know that you have found the cause. I'll rename the issue and pick that up in the next release.

**Comment by stil4m** [comment] 2017-11-03 16:43
Fixed with #101. This is currently replaced with a DOT file which fixes this issue.

**Closed by stil4m** 2017-11-03 16:43 UTC
Labels: bug
